# Generated by Django 4.1 on 2023-04-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('father_name', models.CharField(max_length=100, verbose_name='نام پدر')),
                ('role', models.IntegerField(verbose_name='نقش')),
                ('password_hash', models.CharField(max_length=255, verbose_name='رمز عبور')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.IntegerField(verbose_name='نوع ثبت نام')),
                ('entry_semester', models.IntegerField(verbose_name='نیمسال تحصیلی ورود')),
                ('department_major_level', models.IntegerField(verbose_name='دپارتمان_گرایش_مقطع')),
                ('has_graduated', models.BooleanField(verbose_name='فارغ از تحصیل شده است؟')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.person')),
            ],
        ),
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pomail', models.CharField(max_length=200, verbose_name='ایمیل')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.person')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(max_length=200, verbose_name='ایمیل')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.person')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=200, verbose_name='ایمیل')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.person')),
            ],
        ),
    ]
